FROM nvidia/cuda:11.5.0-runtime-centos7
# Set system ASCII language
ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

# Configure official repo
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Base.repo \
    && sed -i 's/#baseurl/baseurl/g' /etc/yum.repos.d/CentOS-Base.repo

# Install chrony service
RUN yum -y install chrony

# Install git lfs
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash \
    && yum install -y git-lfs \
    && git lfs install

# Install crontab
RUN yum install -y cronie && yum clean all

# Install the libs for OpenCV
RUN yum -y install libXext libSM libXrender \
    && yum clean all

# For molecule tests
RUN yum makecache fast && yum install -y python sudo yum-plugin-ovl bash firewalld \
    && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all;
