version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=password

  app:
    build: app
    restart: always

  web:
    build: web
    restart: always
    ports:
      - '80:80'

  cypress_tests:
    image: cypress/included:9.2.1
    volumes:
      - ./cypress_tests:/tests
    working_dir: /tests
    depends_on:
      - web
      - db
      - app
volumes:
  db-data: